#!/bin/sh
# stash unstaged changes, run release task, stage release updates and restore stashed files

NAME=$(git branch | grep '*' | sed 's/* //')

# don't run on rebase
if [ "$NAME" != '(no branch)' ]
then
  STASH_OUTPUT=$(git stash --keep-index)

  grunt precommit

  RETVAL=$?

  if [ "$STASH_OUTPUT" != "No local changes to save" ]
  then
    git stash pop -q
  fi

  if [ $RETVAL -ne 0 ]
  then
    exit 1
  fi

fi