module.exports = [
  {'text':'Scratch'},
  {'text':'Java'},
  {'text':'Python'},
  {'text':'Ruby'},
  {'text':'Perl'},
  {'text':'PHP'},
  {'text':'HTML'},
  {'text':'Javascript'},
  {'text':'NodeJS'},
  {'text':'AngularJS'},
  {'text':'C#'},
  {'text':'C++'},
  {'text':'Processing'},
  {'text':'C'},
  {'text':'Go'},
  {'text':'CSS'},
  {'text':'Lua'},
  {'text':'Bash'},
  {'text':'Haskell'},
  {'text':'Scala'},
  {'text':'Objective C'},
  {'text':'SQL'},
  {'text':'MySQL'},
  {'text':'Swift'},
  {'text':'R'},
  {'text':'Clojure'},
];

